# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PipelineFlask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Teste 
      run: coverage run app_test.py

    - name: Relatorio do teste
      run: coverage report -m

    # - name: Render Deploy Action
    #   uses: johnbeynon/render-deploy-action@v0.0.8
    #   with:
    #     service-id: <Service-id>
    #     api-key: <Api-Key>

    - name: Deploy no EC2
      run: |
            echo "Conectando aO EC2"
            echo "${{ secrets.AWS_KEY_EXERCICIO }}" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ec2-18-205-107-253.compute-1.amazonaws.com "
            cd exercicio_flask_aws_teste/;git pull;./executar.sh;"




